### ISSUE TITLE
unsplash数据集

### ISSUE THREAD

**Issue by ZHOUGUOKANG** [Yang-Shiqin/Yang-Shiqin#1]
朋友你有 unsplash 的完整数据集吗？我在官网申请没得到回复，最近在做机器学习的一些东西，想要收集一些高清图

**Comment by Yang-Shiqin** [comment]
我有，但我不知道该怎么给你

**Comment by ZHOUGUOKANG** [comment]
我给你一个阿里云oss的文件上传链接，你可以上传到上面吗，可能这样比网盘速度快些，方便加个微信吗？我手机号17600105851
